version: '3.4'

# docker-compose run model bash

#services lists the number of images and info
#local means the scope of image
#change image name in image(image: <your preferred image name>:latest) and volumes(./:/<your preferred image name>) to the one you prefer
#ensure the image name you choose does not overlap with other images' names

services:
  web: 
    build: . #Uncomment this to rebuild
    #image:  pythonfiles_model
    stdin_open: true
    tty: true
    image: app:latest
    ports:
      - "8000:5000"
    #Let code run
    volumes:
      - .:/app
    ulimits:
      memlock: -1 # set upper limit for how much memory is locked for the container (-1 means lock as much as the container uses)
      stack: 67108864
    shm_size: 32gb # set upper limit for how much shared memory container can use
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]